import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;
import java.net.URL;
import javax.swing.ImageIcon;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentTable.java
 *
 * Created on Sep 7, 2011, 2:08:30 PM
 */
/**
 *
 * @author Kris
 */
public class StudentTable extends javax.swing.JFrame {

    /** Creates new form StudentTable */
    public StudentTable() {
        initComponents();
        setLocationRelativeTo(null); //center the JFrame upon opening
        
          URL iconurl = getClass().getResource("default_logo(1)jpg"); // get image
       if(iconurl != null)
       {
         ImageIcon ic = new ImageIcon(iconurl);
         setIconImage(ic.getImage());    // tell the frame to set is as its icon
        }
        
               //set look and feel
          try{
          String laf = UIManager.getSystemLookAndFeelClassName();
          UIManager.setLookAndFeel(laf); // tell the UIManager to change the look and feel
           SwingUtilities.updateComponentTreeUI(this); // tells swing to update components
        }
          
          catch (Exception ex)
        
        {
          System.out.println("Unable to change look and feel : "+ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collegeSplitPane = new javax.swing.JSplitPane();
        inputPanel = new javax.swing.JPanel();
        lastnameTextField = new javax.swing.JTextField();
        firstnameTextField = new javax.swing.JTextField();
        majorTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        studentinfoTable = new javax.swing.JTable();
        collegeMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        printMenuItem = new javax.swing.JMenuItem();
        fileSeparator = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        addMenuItem = new javax.swing.JMenuItem();
        clearMenuItem = new javax.swing.JMenuItem();
        toolsSeparator = new javax.swing.JPopupMenu.Separator();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Student Information");

        inputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputPanel.setPreferredSize(new java.awt.Dimension(200, 380));

        lastnameLabel.setText("Last Name");

        firstnameLabel.setText("First Name");

        majorLabel.setText("Major");

        emailLabel.setText("Email");

        ageLabel.setText("Age");

        addButton.setText("Add");
        addButton.setToolTipText("Add Student to the table");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setToolTipText("Delete Student from the table");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setToolTipText("Clear all textfields");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(majorLabel)
                    .addComponent(emailTextField)
                    .addComponent(emailLabel)
                    .addComponent(majorTextField)
                    .addComponent(firstnameLabel)
                    .addComponent(lastnameLabel)
                    .addComponent(ageLabel)
                    .addComponent(ageTextField)
                    .addComponent(lastnameTextField)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lastnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(firstnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(majorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(majorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailLabel))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(deleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        collegeSplitPane.setLeftComponent(inputPanel);

        tableScrollPane.setPreferredSize(new java.awt.Dimension(320, 311));

        studentinfoTable.setAutoCreateRowSorter(true);
        studentinfoTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        studentinfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Major", "Email", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studentinfoTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableScrollPane.setViewportView(studentinfoTable);

        collegeSplitPane.setRightComponent(tableScrollPane);

        getContentPane().add(collegeSplitPane, java.awt.BorderLayout.CENTER);

        collegeMenuBar.setBackground(new java.awt.Color(51, 51, 255));
        collegeMenuBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 102, 255))); // NOI18N
        collegeMenuBar.setForeground(new java.awt.Color(0, 51, 255));

        fileMenu.setBackground(new java.awt.Color(51, 51, 255));
        fileMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setMnemonic(KeyEvent.VK_N);
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        printMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printMenuItem.setMnemonic(KeyEvent.VK_P);
        printMenuItem.setText("Print");
        printMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(printMenuItem);
        fileMenu.add(fileSeparator);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        collegeMenuBar.add(fileMenu);

        toolsMenu.setBackground(new java.awt.Color(50, 37, 255));
        toolsMenu.setText("Tools");

        addMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addMenuItem.setMnemonic(KeyEvent.VK_A);
        addMenuItem.setText("Add");
        addMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(addMenuItem);

        clearMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        clearMenuItem.setMnemonic(KeyEvent.VK_C);
        clearMenuItem.setText("Clear");
        clearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(clearMenuItem);
        toolsMenu.add(toolsSeparator);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteMenuItem.setText("Delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        toolsMenu.add(deleteMenuItem);

        collegeMenuBar.add(toolsMenu);

        setJMenuBar(collegeMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
System.exit(0); //exit the program
}//GEN-LAST:event_exitMenuItemActionPerformed

private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed

clearButton.doClick(); //repeat the clear button function
    
DefaultTableModel tm = (DefaultTableModel)studentinfoTable.getModel();
tm.setRowCount(0);  //get default table model and clear the row count

        setTitle("College Student Information");  // restore the title
}//GEN-LAST:event_newMenuItemActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
//set all data fields to ""

lastnameTextField.setText("");
firstnameTextField.setText("");
majorTextField.setText("");
emailTextField.setText("");
ageTextField.setText("");
}//GEN-LAST:event_clearButtonActionPerformed

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    try{
    DefaultTableModel tm = (DefaultTableModel)studentinfoTable.getModel();
    //get the table model
    
        
    String lastname = lastnameTextField.getText();
    String firstname = firstnameTextField.getText();
    String major = majorTextField.getText();
    String email = emailTextField.getText();
    String stuage = ageTextField.getText();
    Integer age = Integer.parseInt(stuage);
    
       if (lastname.equals("") || firstname.equals("")|| major.equals("")|| email.equals("")|| stuage.equals(""))

       {
       JOptionPane.showMessageDialog (this,"All Fields must be filled out!", "Error", JOptionPane.ERROR_MESSAGE);
       return;
       }
       
       if (lastname.equals("") && firstname.equals("")&& major.equals("")&& email.equals("")&& stuage.equals(""))

       {
       JOptionPane.showMessageDialog (this,"All Fields must be filled out!", "Error", JOptionPane.ERROR_MESSAGE);
       return;
       }
           
               
Object[] data = {firstname,lastname,major,email,age};
    //create an array that holds the input in the order of the table
  
    tm.addRow(data); 
    //create new row in table and add  array data
    }
    
    catch(NumberFormatException nfe)
    { JOptionPane.showMessageDialog(this,"All Fields must be filled out!"+"\n Last Name, First Name, Major, and Email must be text inputs "+"\n Age (in years) must be numerical", "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_addButtonActionPerformed

private void addMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemActionPerformed
addButton.doClick();
}//GEN-LAST:event_addMenuItemActionPerformed

private void clearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItemActionPerformed
clearButton.doClick();
}//GEN-LAST:event_clearMenuItemActionPerformed

private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
deleteButton.doClick();
}//GEN-LAST:event_deleteMenuItemActionPerformed

private void printMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMenuItemActionPerformed
  try{
        MessageFormat header = new MessageFormat("Student Data ");
        MessageFormat footer = new MessageFormat("from Student Database");
        studentinfoTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
       
//try to print the JTable
     }
        catch(Exception pe)
            
  //catch the exception Print Error (PE) and show error message          
        {
          JOptionPane.showMessageDialog(this,"Printing failed :"+pe.getMessage());
        }
}//GEN-LAST:event_printMenuItemActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    int row = studentinfoTable.getSelectedRow();
        if(row < 0)  //get selected row from the table, if no row is selected return
            return;
        
        DefaultTableModel tm = (DefaultTableModel)studentinfoTable.getModel();
        tm.removeRow(row); //get Table Model and remove selected row
}//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StudentTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JMenuItem addMenuItem;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JMenuBar collegeMenuBar;
    private javax.swing.JSplitPane collegeSplitPane;
    private javax.swing.JButton deleteButton;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileSeparator;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JTextField majorTextField;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JTable studentinfoTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JPopupMenu.Separator toolsSeparator;
    // End of variables declaration//GEN-END:variables
}
